DROP DATABASE IF EXISTS mean_db;
CREATE DATABASE mean_db;

USE mean_db;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(256) NOT NULL,
  password VARCHAR(256) NOT NULL
);
